### ISSUE TITLE
ImportError: No module named configparser

### ISSUE THREAD

**Issue by maitra** [pklaus/sendmail_python#1]
I get the following error:
```
``$ ./sendmail.py --help
Traceback (most recent call last):
  File "./sendmail.py", line 17, in <module>
    import configparser
ImportError: No module named configparser

```
What is going wrong?

**Comment by pklaus** [comment]
Well, `configparser` is [a Python 3 module](https://docs.python.org/3/library/configparser.html). In Python 2 it was still called [`ConfigParser`](https://docs.python.org/2/library/configparser.html).

As the readme of this project says, it's a "Script to Send E-Mails with Python3", so no Python 2 support unfortunately.

**Comment by maitra** [comment]
Thanks. So, line 17 in  sendmail.py needs to be:` import ConfigParser`

Do you want to correct this, or me to submit a patch?

Btw, is it possible to have sendmail.py read all these details from stdin?

**Comment by pklaus** [comment]
I might consider a pull request or patch, if it works on both, Python 2 and Python 3.

Something along the lines:

```
try:
    import configparser
except ImportError:
    import ConfigParser as configparser
```

I'm not sure, however, if all required email Python modules are there in Python 2...


What concerns reading from stdin:  
You may provide `-` as `MAILBODY` to use stdin for the content.

**Comment by maitra** [comment]
Your suggestions appears to work with python2 and python3, though I am only interested in python3. I will figure out how to do a patch unless you get to it first.

What concerns reading from stdin:
You may provide - as MAILBODY to use stdin for the content.

I will try as suggested. Thanks!

**Comment by pklaus** [comment]
As I already said in [my comment two days ago](https://github.com/pklaus/sendmail_python/issues/1#issuecomment-490377261), this project is made for Python 3. You say, you are only interested in Python 3. The issue you brought up, however, indicates you were using Python 2! So once you use the right version of Python (i.e. 3), you shouln't run into problems of the kind described in this issue.
